<?php


define('MERCI_ERROR_TOO_MANY', 1);
define('MERCI_ERROR_CONFLICT', 2);

function merci_views_data_alter(array &$data) {

  $data['entityref__roles']['table']['join'] = array(
    'node__field_reservable_by' => array(
      'left_field' => 'id',
      'field' => 'target_id',
      'table' => 'user__roles',
    ),
  );
  $data['entityref__roles']['roles_entity_ref_target_id'] = array(
    'title' => t('Roles'),
    'help' => t('Roles that a user belongs to.'),
    'argument' => array(
      'id' => 'user__roles_rid',
      'name table' => 'role',
      'name field' => 'name',
      'empty field name' => t('No role'),
      'zero is null' => TRUE,
      'numeric' => TRUE,
    ),

  );
}

/**
 *  * Implements hook_entity_bundle_field_info_alter().
 */
function merci_entity_bundle_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type, $bundle) {
  foreach ($fields as $name => $field) {
    if ($field instanceof \Drupal\field\Entity\FieldConfig && ($settings = $field->getThirdPartySettings('merci'))) {
      foreach ($settings as $constraint => $setting) {
        $fields[$name]->addConstraint($constraint, $setting);
      }
    }
  }
}
